Option to Parse JSON in environment variables
ngx-rocket/scripts pull request #24
Opened 2021-02-11 17:49 UTC by cnuss

I have a case where I have a more complex object I'd like to inject into the environment, such as a map of multiple micro services:

```
{
"Service1ApiUrl": "https://example.com/service1/api",
"Service2ApiUrl": "https://example.com/service2/api"
}
```

This would be saved as an escaped JSON string in the environment:

```
export TEST_ENV_VAR="hello world"
export TEST_JSON_ENV_VAR="{\"Service1ApiUrl\":\"https:\/\/example.com\/service1\/api\",\"Service2ApiUrl\":\"https:\/\/example.com\/service2\/api\"}"
```

This PR allows for the parsing of JSON strings, if the `--parseJson` flag is set.

Before + Backwards Compatible, without the flag: 

`./bin/ngx-scripts env TEST_ENV_VAR TEST_JSON_ENV_VAR`:

```
export const env: { [s: string]: (string | null); } = {
  'TEST_ENV_VAR': 'hello world',
  'TEST_JSON_ENV_VAR': '{"Service1ApiUrl":"https:\\/\\/example.com\\/service1\\/api","Service2ApiUrl":"https:\\/\\/example.com\\/service2\\/api"}'
};
```

NEW with the flag:

`./bin/ngx-scripts env TEST_ENV_VAR TEST_JSON_ENV_VAR --parseJson`:

```
export const env: { [s: string]: (any | null); } = {
  'TEST_ENV_VAR': 'hello world',
  'TEST_JSON_ENV_VAR': {
    'Service1ApiUrl': 'https://example.com/service1/api',
    'Service2ApiUrl': 'https://example.com/service2/api'
  }
};
```

Notable changes:
 - Object type is now `any`
 - JSON is parsed, if possible, otherwise fallback to original logic

Thoughts? Feelings? Feedback?

2021-02-11 17:50 UTC, cnuss commented
@sinedied Pinging you as the main contributor to this repo. What do you think of the `--parseJson` flag?

2021-02-15 16:38 UTC, cnuss commented
hiya @sinedied any thoughts on this PR?

2021-02-22 10:37 UTC, sinedied commented
Thanks for the PR! 👍 
Could you rename the flag `--parseJson` to `--parse-json` to match the naming scheme of other CLI flags?

I'll merge it and release a new version after this change.
I'll also look at the CI to see why it's not running the tests.

2021-03-03 11:21 UTC, sinedied requested changes
I suggested the changes for renaming the option, you just have to accept them.

2021-03-03 11:21 UTC, sinedied commented on index.js
> +)} <env_var> [<env_var2> ...] [--out <file>] [--format json|js] [--parseJson]
```suggestion
)} <env_var> [<env_var2> ...] [--out <file>] [--format json|js] [--parse-json]
```

2021-03-03 11:21 UTC, sinedied commented on README.md
> +- `--parseJson`: During `env`, if an environment variable's value is parsable JSON, it will be a proper object in `.env.ts`
```suggestion
- `--parse-json`: During `env`, if an environment variable's value is parsable JSON, it will be a proper object in `.env.ts`
```

2021-03-03 11:21 UTC, sinedied commented on README.md
> +`ngx-scripts env <env_var> [<env_var2> ...] [--out <file>] [--format json|js] [--parseJson]`
```suggestion
`ngx-scripts env <env_var> [<env_var2> ...] [--out <file>] [--format json|js] [--parse-json]`
```

2021-03-03 11:21 UTC, sinedied commented on index.js
> +        'parseJson'
```suggestion
        'parse-json'
```

2021-03-03 11:21 UTC, sinedied commented on index.js
> +          this._options.parseJson
```suggestion
          this._options['parse-json']
```

2021-03-04 04:24 UTC, cnuss commented
merged, thanks for making the change for me! I missed your initial comment!

2021-03-12 02:48 UTC, cnuss commented
@sinedied just a reminder, I think we're good to merge, right?

2021-03-12 08:38 UTC, sinedied approved these changes

2021-03-12 08:39 UTC, sinedied commented
Good call, I got stuck on other things sorry. Let's merge this and thank you for this! 👍

2021-03-12 08:41 UTC, merged